config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', sessions: 'users/sessions'  }
  scope "(:locale)", :locale => /en|ru|ar|ch|sp|fr|it/ do
    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
    resources :reports do 
      collection do
        get :recapcha_submit
      end
    end
    resources :replies
    mount Ckeditor::Engine => '/ckeditor'
    resources :sub_categories do
      collection do
        get :disclaimer
        get :disclaimer_2
        get :subcat
      end
    end
    resources :categories do
      collection do
        get :catpage
        get :search
      end
    end
    resources :cities
    resources :states
    resources :countries
    resources :continents
    resources :charges, only: [:new, :create] do
      collection do
        get :pay
        get :specific
      end
    end
   
    
    root 'dashboard#main'
    get 'dashboard/catshow'
    get 'dashboard/show'
    get  'dashboard/signout'
    get  'dashboard/decide'
    get  'dashboard/search'
    get 'dashboard/conshow'
    #root 'post_ads#index'
    resources :post_ads do
      collection do
        get :published_adz
      end
    end
    get 'dashboard/login_page'
    get 'dashboard/store'
    get 'dashboard/giveaway'
    get 'dashboard/contact_us'
    get 'dashboard/about_us'
    get 'dashboard/terms'
    get 'dashboard/privacy'
    get 'reports/recaptcha'
    resources :user_informations do 
      collection do
        get :page 
      end
    end
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :sub_categories
  has_many :post_ads
end

app/models/city.rb
class City < ApplicationRecord
  has_many :categories
  belongs_to :country
  has_many :post_ads
end

app/models/continent.rb
class Continent < ApplicationRecord
  has_many :countries
  has_many :post_ads
  translates :name, touch: true, :fallbacks_for_empty_translations => true
end

app/models/country.rb
class Country < ApplicationRecord
  has_many :cities
  belongs_to :continent
  has_many :post_ads
end

app/models/dashboard.rb
class Dashboard < ApplicationRecord
	enum page_type: {contact_us: 0, about_us: 1, terms: 2, privacy: 3}
end

app/models/post_ad.rb
class PostAd < ApplicationRecord
  mount_uploaders :avatars, ImageUploader
  belongs_to :user
  enum status: {running: 0,stopped: 1}
  belongs_to :sub_category
  has_many :replies, dependent: :destroy
  has_many :reports, dependent: :destroy
  has_one_attached :clip
  #mount_uploader :video, VideoUploader 
  # belongs_to :continent
  # belongs_to :country
  # belongs_to :state
  belongs_to :city
  belongs_to :category
  # belongs_to :user
end

app/models/reply.rb
class Reply < ApplicationRecord
  belongs_to :user
  belongs_to :post_ad
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :user
  belongs_to :post_ad
end

app/models/state.rb
class State < ApplicationRecord
  has_many :cities
  belongs_to :country
  has_many :post_ads
end

app/models/sub_category.rb
class SubCategory < ApplicationRecord
  has_many :post_ads
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :omniauthable, omniauth_providers: [:google_oauth2]
  has_many :post_ads
  has_many :replies
  has_one  :user_information
  

  def self.from_google(email:, full_name:, uid:, avatar_url:)
    return nil if email.blank?
    create_with(uid: uid, full_name: full_name, avatar_url: avatar_url).find_or_create_by!(email: email)
  end
  
  
end

app/models/user_information.rb
class UserInformation < ApplicationRecord
	belongs_to :user
	WHITELIST_PARAMS = [:name, :email, :address, :phone, :zipcode, :user_id]
	
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  skip_before_action :authenticate
  
  def show
  	@continents = Continent.all.includes(:countries)
    @category = Category.find_by(id: params[:id])
    
  end
  def conshow
    @category_id = params[:category_id]
    @sub_category_id = params[:sub_category]
    @continents = Continent.all.includes(:countries)  
  end
  
  def login_page
    @reply = params[:reply] if params[:reply].present?
    @giveaway = params[:giveaway] if params[:giveaway].present?
    @id = params[:id] if params[:id].present?
  end
  def store
  end
  def main
    
  end
  def search
  	@cities = City.where('name ILIKE ?', "%#{params[:search]}%")
  end
  def about_us
    @description = Dashboard.about_us.first.description
  end
  def contact_us
    @description = Dashboard.contact_us.first.description
  end
  def privacy
    @description = Dashboard.privacy.first.description
  end
  def terms
    @description = Dashboard.terms.first.description
  end
  def decide
  	@cat_id = params[:cat_id]
  	@city_id = params[:city_id]
  	@category_id = params[:category_id]
  end

  def signout
  	session[:id] = nil
  	redirect_to root_path
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/continents_helper.rb
module ContinentsHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/post_ads_helper.rb
module PostAdsHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/views/dashboard/about_us.html.erb
<div class="container" style="width: auto; background-color: black; margin: 40px 50px 0px 50px;">
		<center style= "margin: 0px -50px 0px -50px;"><div style="background-color: white; width: 70%; border: 5px solid red;">
			<center><h1>About Us</h1></center>
		    <div class="container about" style="margin: auto; width: 95%; border: 1px solid black; margin-bottom: 20px;">
			   <p  style="width: auto;"><p style="text-align: left; font-size: 15px; line-height: 30px; color: black; width: auto;"><span><%= t('about_us_page')%> </span> <a href="postadz.com">PostAdz.com</a><span><%= t('about_us_page2') %> </span></p></p>
			</div>
	    </div></center>
	</div>

app/views/dashboard/conshow.html.erb
<div class="container" style="margin-top: 30px;">
	<%if current_user.present?%>
     <%= link_to t('manage_ad_btn_con'), post_ads_path, :class=>"btn", :style => " background-color: white; font-weight: bold; color: black; float: right;" %>
     <%if current_user.is_admin?%>
     <%= link_to t('report_ad_btn_con'), reports_path, :class=>"btn", :style => "font-weight: bold; color: black; float: right; background-color: white; margin-right: 10px;" %>
     <%end%>
  <%end%>
<%= form_tag :dashboard_search, method: :get do %>
  <%= text_field_tag :search, nil, class:"form-control fa fa-search", placeholder: t('search_by_con'), required: true, :id => "mysearch"%>
<%end%>	
<div style="background-color: white; margin-bottom: 40px; border: 3px solid red;">
	<div class="row" style="margin: 1px; line-height: 2;">
		<% @continents&.each do |con|%>
		<div class="col-sm-6">
			<div data-toggle="collapse" data-target=".lp<%= con.id%>" style="background-color: #F3F6FB; font-size: 25px; border-radius: 5px; margin-bottom: 2px; padding-left: 10px; color: red;"><b class="noselect"><%= con&.name%></b></div>
			<% con.countries.includes(:cities)&.order("name ASC").each do |country|%>
			<div class="collapse lp<%= con.id %>">
			<div class="col-md-4">
			  <p style="color:white;"><h4><%= country&.name %></h4></p>
			  <% country.cities.order("name ASC").each do |city|%>
			   <% if current_user.present? %>
			    <p><%= link_to city.name, new_post_ad_path(category_id: @category_id, cat_id: @sub_category_id, city_id: city.id), :style => "color: black;"%></p>
			    <% else %>
			    	<p><%= link_to city.name, published_adz_post_ads_path(category_id: @category_id, cat_id: @sub_category_id, city_id: city.id), :style => "color: black;"%></p>
			    <% end %>
			  <%end%>
			  </div>
			  </div>
			<%end%>
		</div>
		<%end%>
	</div>
</div>
</div>

app/views/dashboard/contact_us.html.erb
<div class="container" style="width: auto; background-color: black; margin: 40px 50px 0px 50px;">
	<center style= "margin: 0px -50px 0px -50px;"><div class="contact_us" style="background-color: white; width: 50%; border: 5px solid red;">
		<center><h1><%= t('contact')%></h1></center>
		<div class="container" style="width: auto; background-color: white; padding-bottom: 20px; margin-bottom: 20px;">
					<p style="width: auto;">
						
						<p style="color: black; font-size: 20px;"><%= t('email_contact_us')%> <a class= "btn btn-default" href= "mailto:Support@PostAdz.com" target ="_blank"><%= t('send_email')%></a></p>
							<p style="color: black; font-size: 20px;"><%= t('call_us')%> <a class ="btn btn-default" href = "tel:+19147050000"> 1-914-705-0000</a></p>
							<p style="color: black; font-size: 20px;">
								<%= t('whatsapp')%> <a class = "btn btn-default" href="https://api.whatsapp.com/send?phone=+19147050000"><%= t('send_msg')%></a>
							</p>
					</p>
		</div>
	</div></center>
</div>

app/views/dashboard/decide.html.erb
<div class="page">
		<div class="ad-post-wrapper section">
			<div class="container" >
				<div class="row loginform" >
					<div class="col-md-4 col-md-offset-4" >
						<div class="user-form" style="text-align: center; font-size: 40px; background-color: black;">
							<form >
							    <div class="form-group" style="margin-top: 40px;">
							    	 <%=link_to "View Pubished Ads", published_adz_post_ads_path(cat_id: @cat_id, city_id: @city_id, category_id: @category_id), :style=>"color: red;", :class => "posthead btn btn-primary"%>
							    	 <p style="padding-top: 10px; color: white;">OR</p>
							    	 <%=link_to "Publish Your Ad", new_post_ad_path(cat_id: @cat_id, city_id: @city_id, category_id: @category_id),  :style=>"color: red;", :class => "posthead btn btn-primary"%>
							    </div>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div> <!-- ad-post -->
	</div>	<!-- page -->

app/views/dashboard/giveaway.html.erb
<div style="margin: 50px;">
	<center><h1>Coming Soon!</h1></center>
	<center><h4>We are still working on Giveaway!</h4></center>
</div>

app/views/dashboard/login_page.html.erb
<div class="page">
		<div class="ad-post-wrapper section">
			<div class="container">
				<div class="row loginform" >
					<div class="col-md-4 col-md-offset-4 logindiv" >
						<div class="user-form" style="text-align: center; font-size: 40px; background-color: black;">
							<form >
							    <div class="form-group">
							    	<%= image_tag("new111.png", :alt => "Logo", :style => "width: 150px;") %>
							    </div>
							    <div class="form-group">
							    	 <strong><h4 style="color: yellow;"><%= t('sign_in')%></h4></strong>
							    </div>
							    <% if @giveaway %>
							    	<a class = "loginimg" href="<%= user_google_oauth2_omniauth_authorize_path(giveaway: @giveaway) %>">
							    		<%= image_tag("gmaillogin.png", :alt => "Gmail", :style => "border-radius: 3px; width: 200px; height: 50px;") %>
							    	</a>
							    <% else %>
							    	<a class = "loginimg" href="<%= user_google_oauth2_omniauth_authorize_path(reply: @reply, id: @id) %>">
							    		<%= image_tag("gmaillogin.png", :alt => "Gmail", :style => "border-radius: 3px; width: 200px; height: 50px;") %>
							    	</a>
							    <% end %>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div> <!-- ad-post -->
	</div>	<!-- page -->

app/views/dashboard/main.html.erb
<div class="container" style="background-color: black;  margin-top: 50px; margin-bottom: 80px;">
		<center><div class="iphone" style="margin-top: 40px;">
			<button class="mainbtn btn1"><%= link_to t('search_by_con_main'), dashboard_show_path, :class => "btn btn-default", :style => " color: red; border: 8px solid red; padding-left: 14px; width: auto; font-size: 20px; font-weight: bold;" %></button><br><span style="font-size: 23px; font-weight: bold;"><%= t('or_txt_main')%></span><br>
			<button class="mainbtn btn2"><%= link_to t('search_by_cat_main'), catpage_categories_path, :class => "btn btn-default", :style => " color: red; border: 8px solid red; padding-top: border-radious: none; 12px; width: auto; font-size: 20px; font-weight: bold;" %> </button>
		</div></center>
</div>

app/views/dashboard/privacy.html.erb
<div class="container" style="width: auto; background-color: black; margin: 40px 50px 0px 50px;">
	
	<center style= "margin: 0px -50px 0px -50px;"><div style="background-color: white; width: 70%; border: 5px solid red;">
		<center><h1>Privacy Policy</h1></center>
	    <div class="container about" style="margin: auto; width: 95%; color: black; text-align: left; border: 1px solid black; margin-bottom: 20px;">
		   <p  style="width: auto; font-size: 20px;"><p style="text-align: justify; font-size: 15px; line-height: 30px; color: black; width: auto;">
				<%= t('pp1')%> <h4><%= t('privacy')%> </h4>

				<h4><%= t('accept')%></h4>
				<p><%= t('pp2')%> </p>

				<h4><%= t('pcollection')%></h4>
				<p><%= t('pp3')%></p>
				<%= t('pspan1')%>
				<h4><%= t('pproved')%></h4>
				<li><%= t('pli1')%></li>
				<li><%= t('pli2')%></li>
				<li><%= t('pli3')%></li>
				<li><%= t('pprocess')%></li>
				<h4><%= t('pimprove')%> <a href ="postadz.com">PostAdz.com </a></h4>
				<p><%= t('pp4')%></p>
				  
				<p><%= t('pp5')%></p>




				<h4><%= t('pdisclosure')%> </h4>

				<p><%= t('pp6')%> </p>
				<li> <%= t('pli4')%></li>
				 <li> <%= t('pli5')%></li> 
				<li> <%= t('pli6')%></li>
				 <li> <%= t('pli7')%> </li>
				<li><%= t('pli8')%></li>
				 <li> <%= t('pli9')%></li>
				 <li> <%= t('pli10')%><li>
				<li><%= t('pli11')%><li>
				<%= t('pspan2')%>

				<h4><%= t('pdisclosure2')%></h4>

				<p><%= t('pp7')%></p>
				<li> <%= t('pli12')%></li>
				<li> <%= t('pli13')%></li>
				<li> <%= t('pli14')%></li>
				<li> <%= t('pli15')%></li>
				 <li> <%= t('pli16')%></li>
				<p> <%= t('pp8')%></p>

				<h4><%= t('assort')%></h4>

				<p><%= t('pp9')%></p>
				<li> <%= t('pli17')%></li>
				<li> <%= t('pli18')%> </li>
				<li><%= t('pli19')%></li>
				<p><%= t('pp10')%></p>

				<p><%= t('pp11')%></p>

				<h4><%= t('communication')%></h4>

				<p><%= t('pp12')%> </p>

				<h4><%= t('corress')%></h4>

				<p><%= t('pp13')%></p>
				Contact Us: 
				Email: <a href = "linkto:admin@postadz.com" target = "_blank">admin@Postadz.com</a>
				Phone: 1-914-705-0000



				 <h4><%= t('adult')%></h4>

				<p><a href="postadz.com">PostAdz.com</a> <%= t('pp14')%></p>
				<p><%= t('pp15')%></p>

				<h4><%= t('plink')%> </h4>

				<p><a href="postadz.com">PostAdz.com</a> <%= t('pspan3')%> <a href="postadz.com">PostAdz.com</a> <%= t('pspan4')%> <a href="postadz.com">PostAdz.com</a> <%= t('pspan5')%><a href="postadz.com">PostAdz.com</a> <%= t('pspan6')%> <a href="postadz.com">PostAdz.com</a> ) <%= t('pspan7')%></p>

				<h4><%= t('pecom')%> </h4>

				<p><%= t('pspan8')%> <a href="postadz.com">PostAdz.com</a> are processed through our secure server in order to make every reasonable effort to insure that your personal information is protected. </p>
				<p>Please know that <a href="postadz.com">PostAdz.com</a> <%= t('pspan9')%><a href="postadz.com">PostAdz.com</a> control. We cannot guarantee the security of the info on and sent from <a href="postadz.com">PostAdz.com</a> . </p>
				<p>On <a href="postadz.com">PostAdz.com</a> , <%= t('pspan10')%> </p>

				<h4><%= t('ppolicy')%> </h4>

				<p><%= t('pspan11')%> <a href="postadz.com">PostAdz.com</a> <%= t('pspan12')%> </p>


				<h4><%= t('pmore')%></h4
				<p> e-mail us  <a href = "linkto:support@postadz.com" target = "_blank">support@PostAdz.com</a> <%= t('pspan13')%></p>
				</p></p>
		</div>
	</div></center>
</div>

app/views/dashboard/search.html.erb
<div class="container">
  <div class="row" style="margin: 1px;">
    <div class="col-md-6">
      <div style="background-color: #F3F6FB; font-size: 25px; border-radius: 5px; margin-bottom: 2px; padding-left: 10px; color: red;"></div>
      <% if @cities.present? %>
      <% @cities&.each do |city|%>
        <p><%= link_to city&.name, categories_path(id: city.id)%></p>
      <%end%>
      <%else%>
       <H3>No Results found!</H3>
      <%end%>
    </div>
  </div>

</div>

app/views/dashboard/show.html.erb
<div class="container" style="margin-top: 30px;">
	<%if current_user.present?%>
     <%= link_to t('manage_btn_show'), post_ads_path, :class=>"btn", :style => " background-color: white; font-weight: bold; color: black; float: right;" %>
     <%if current_user.is_admin?%>
     <%= link_to t('view_reported_btn_show'), reports_path, :class=>"btn", :style => "font-weight: bold; color: black; float: right; background-color: white; margin-right: 10px;" %>
     <%end%>
  <%end%>
<%= form_tag :dashboard_search, method: :get do %>
  <%= text_field_tag :search, nil, class:"form-control fa fa-search", placeholder: t('search_dash_show'), required: true, :id => "mysearch"%>
<%end%>	
<div style="background-color: white; margin-bottom: 40px; border: 3px solid red;">
	<div class="row" style="margin: 1px; line-height: 2;">
		<% @continents&.each do |con|%>
		<div class="col-sm-6">
			<div data-toggle="collapse" data-target=".lp<%= con.id%>" style="background-color: #F3F6FB; font-size: 25px; border-radius: 5px; margin-bottom: 2px; padding-left: 10px; color: red;"><b class="noselect"><%= con&.name%></b></div>
			<% con.countries.includes(:cities)&.order("name ASC").each do |country|%>
			<div class="collapse lp<%= con.id %>">
			<div class="col-md-4">
			  <p style="color:white;"><h4><%= country&.name %></h4></p>
			  <% country.cities.order("name ASC").each do |city|%>
			    <p><%= link_to city.name, categories_path(id: city.id), :style => "color: black;"%></p>
			  <%end%>
			  </div>
			  </div>
			<%end%>
		</div>
		<%end%>
	</div>
</div>
</div>

app/views/dashboard/store.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<style>
		#slideshow { 
  margin: 50px auto; 
  position: relative; 
  width: 240px; 
  height: 340px; 
  padding: 10px; 
  box-shadow: 0 0 20px rgba(0,0,0,0.4); 
}

#slideshow > div { 
  position: absolute; 
  top: 10px; 
  left: 10px; 
  right: 10px; 
  bottom: 10px; 
}

#slideshow1 { 
  margin: 50px auto; 
  position: relative; 
  width: 240px; 
  height: 340px; 
  padding: 10px; 
  box-shadow: 0 0 20px rgba(0,0,0,0.4); 
}

#slideshow1 > div { 
  position: absolute; 
  top: 10px; 
  left: 10px; 
  right: 10px; 
  bottom: 10px; 
}

#slideshow2 { 
  margin: 50px auto; 
  position: relative; 
  width: 240px; 
  height: 340px; 
  padding: 10px; 
  box-shadow: 0 0 20px rgba(0,0,0,0.4); 
}

#slideshow2 > div { 
  position: absolute; 
  top: 10px; 
  left: 10px; 
  right: 10px; 
  bottom: 10px; 
}

#slideshow3 { 
  margin: 50px auto; 
  position: relative; 
  width: 240px; 
  height: 340px; 
  padding: 10px; 
  box-shadow: 0 0 20px rgba(0,0,0,0.4); 
}

#slideshow3 > div { 
  position: absolute; 
  top: 10px; 
  left: 10px; 
  right: 10px; 
  bottom: 10px; 
}

#slideshow4 { 
  margin: 50px auto; 
  position: relative; 
  width: 240px; 
  height: 340px; 
  padding: 10px; 
  box-shadow: 0 0 20px rgba(0,0,0,0.4); 
}

#slideshow4 > div { 
  position: absolute; 
  top: 10px; 
  left: 10px; 
  right: 10px; 
  bottom: 10px; 
}
	</style>
	
</head>
<body>
	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.5.2/jquery.min.js"></script>
	<div id="wrap">
	<div id="columns" class="columns_3">
  <figure>
  <div id="slideshow">
  <div>
    <img src="/assets/cap1.jpeg">
  </div>
  <div>
    <img src="/assets/cap2.jpeg">
  </div>
  <div>
    <img src="/assets/cap3.jpeg">
  </div>
</div>
	<figcaption style="font-size: 16px;"><%= t('item1_txt') %></figcaption>
    <span class="price">$25</span>
    <a class="button" href="#"><%= t('order_btn_store') %></a>
	</figure>
	
	<figure>
	<div id="slideshow1">
	  <div>
	    <img src="/assets/black_shirt_frnt.jpeg">
	  </div>
	  <div>
	    <img src="/assets/black_shirt_bck.jpeg">
	  </div>
	</div>
	<figcaption style="font-size: 16px;"><%= t('item2_txt') %></figcaption>
    <span class="price">$20</span>
    <a class="button" href="#"><%= t('order_btn_store') %></a>
	</figure>
	
  <figure>
	<div id="slideshow2">
	  <div>
	    <img src="/assets/gray_frnt.jpeg">
	  </div>
	  <div>
	    <img src="/assets/gray_bck.jpeg">
	  </div>
	</div>
	<figcaption style="font-size: 16px;"><%= t('item3_txt') %></figcaption>
    <span class="price">$20</span>
    <a class="button" href="#"> <%= t('order_btn_store') %></a>
	</figure>
  
	<figure>
	<div id="slideshow3">
	  <div>
	    <img src="/assets/black_hoddie_frnt.jpeg">
	  </div>
	  <div>
	    <img src="/assets/black_hoddie_bck.jpeg">
	  </div>
	</div>
	<figcaption style="font-size: 16px;"><%= t('item4_txt') %></figcaption>
    <span class="price">$68</span>
    <a class="button" href="#"><%= t('order_btn_store') %></a>
	</figure>
	
   <figure>
	 <div id="slideshow4">
	  <div>
	    <img src="/assets/gray_hoddie_frnt.jpeg">
	  </div>
	  <div>
	    <img src="/assets/gray_hoddie_bck.jpeg">
	  </div>
	</div>
	<figcaption style="font-size: 16px;"><%= t('item5_txt') %></figcaption>
    <span class="price">$68</span>
    <a class="button" href="#"><%= t('order_btn_store') %></a>
	</figure>
</div>
</div>


</body>
</html>
<script >
	$("#slideshow > div:gt(0)").hide();

	setInterval(function() {
	  $('#slideshow > div:first')
	    .fadeOut(500)
	    .next()
	    .fadeIn(500)
	    .end()
	    .appendTo('#slideshow');
	}, 5000);
	$("#slideshow1 > div:gt(0)").hide();

	setInterval(function() {
	  $('#slideshow1 > div:first')
	    .fadeOut(500)
	    .next()
	    .fadeIn(500)
	    .end()
	    .appendTo('#slideshow1');
	}, 6000);

$("#slideshow2 > div:gt(0)").hide();

	setInterval(function() {
	  $('#slideshow2 > div:first')
	    .fadeOut(500)
	    .next()
	    .fadeIn(500)
	    .end()
	    .appendTo('#slideshow2');
	}, 8000);

$("#slideshow3 > div:gt(0)").hide();

	setInterval(function() {
	  $('#slideshow3 > div:first')
	    .fadeOut(400)
	    .next()
	    .fadeIn(400)
	    .end()
	    .appendTo('#slideshow3');
	}, 4000);

$("#slideshow4 > div:gt(0)").hide();

	setInterval(function() {
	  $('#slideshow4 > div:first')
	    .fadeOut(400)
	    .next()
	    .fadeIn(400)
	    .end()
	    .appendTo('#slideshow4');
	}, 6000);


</script>

app/views/dashboard/terms.html.erb
<div class="container" style="width: auto; background-color: black; margin: 40px 50px 0px 50px;">
	
	<center style= "margin: 0px -50px 0px -50px;"><div style="background-color: white; width: 70%; border: 5px solid red;">
		<center><h1>Terms & Conditions</h1></center>
		    <div class="container about" style="margin: auto; width: 95%; color: black; text-align: left; border: 1px solid black; margin-bottom: 20px;">
		   <p  style="width: auto; font-size: 20px;">
		   		<p><a href="postadz.com">PostAdz.com</a><%= t('para1_terms')%></p>
				<p><%= t('para2_terms')%></p>

				<h4><%= t('user_conduct')%></h4>

				<p><%= t('p3')%><p>
				<li> <%= t('li1')%></li>
				<li> <%= t('li2')%></li>
				<li> <%= t('li3')%></li>
				<li>
				<%= t('li_a')%> <br>
				<%= t('li_b')%><br>
				<%= t('li_c')%><br>
				<%= t('li_d')%><br>
				<%= t('li_e')%></li>
				<li> <%= t('li4')%></li>
				<li><%= t('li5')%></li>
				<li> <%= t('li6')%></li>
				<li> <%= t('li7')%></li>
				<li> <%= t('li8')%></li>
				<li> <%= t('li9')%></li>
				<li> <%= t('li10')%></li>
				<li> <%= t('li11')%></li>
				<li> <%= t('li12')%> </li>
				<li> <%= t('li13')%></li>
				<li><%= t('li14')%></li>
				<li><%= t('li15')%></li>
				<li> <%= t('li16')%></li>
				<li><%= t('li17')%></li>
				<li> <%= t('li18')%></li>
				<li> <%= t('li19')%></li>
				<li> <%= t('li20')%></li>


				<%= t('span1')%> <a href="linkto:admin@postadz.com" target = "_blank">Admin@postadz.com</a>
				<%= t('span2')%>


				<h4><%= t('use_material')%></h4>
				<p><%= t('p4')%></p>


				<h4><%= t('fair_housing')%></h4>
				<p><%= t('p5')%></p>
				<p><%= t('p6')%></p>

				<h4><%= t('termination')%> </h4>
				<p><%= t('p7')%></p>

				<h4><%= t('no_third')%></h4>
				<p><%= t('p8')%></p>

				<h4><%= t('copyright')%></h4>
				<p><%= t('p9')%></p>
				<p><%= t('p10')%></p>
				<li><%= t('li21')%></li>
				<li><%= t('li22')%></li>
				<li> <%= t('li23')%></li>
				<li> <%= t('li24')%></li>
				<li><%= t('li25')%> </li>
				<li> <%= t('li26')%></li>
				<p><%= t('p10')%><a href="linkto:admin@postadz.com" target = "_blank">Admin@postadz.com</a> <%= t('p11')%></p>
		   </p>
		</div>
	</div></center>
</div>