config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', sessions: 'users/sessions'  }
  scope "(:locale)", :locale => /en|ru|ar|ch|sp|fr|it/ do
    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
    resources :reports do 
      collection do
        get :recapcha_submit
      end
    end
    resources :replies
    mount Ckeditor::Engine => '/ckeditor'
    resources :sub_categories do
      collection do
        get :disclaimer
        get :disclaimer_2
        get :subcat
      end
    end
    resources :categories do
      collection do
        get :catpage
        get :search
      end
    end
    resources :cities
    resources :states
    resources :countries
    resources :continents
    resources :charges, only: [:new, :create] do
      collection do
        get :pay
        get :specific
      end
    end
   
    
    root 'dashboard#main'
    get 'dashboard/catshow'
    get 'dashboard/show'
    get  'dashboard/signout'
    get  'dashboard/decide'
    get  'dashboard/search'
    get 'dashboard/conshow'
    #root 'post_ads#index'
    resources :post_ads do
      collection do
        get :published_adz
      end
    end
    get 'dashboard/login_page'
    get 'dashboard/store'
    get 'dashboard/giveaway'
    get 'dashboard/contact_us'
    get 'dashboard/about_us'
    get 'dashboard/terms'
    get 'dashboard/privacy'
    get 'reports/recaptcha'
    resources :user_informations do 
      collection do
        get :page 
      end
    end
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :sub_categories
  has_many :post_ads
end

app/models/city.rb
class City < ApplicationRecord
  has_many :categories
  belongs_to :country
  has_many :post_ads
end

app/models/continent.rb
class Continent < ApplicationRecord
  has_many :countries
  has_many :post_ads
  translates :name, touch: true, :fallbacks_for_empty_translations => true
end

app/models/country.rb
class Country < ApplicationRecord
  has_many :cities
  belongs_to :continent
  has_many :post_ads
end

app/models/dashboard.rb
class Dashboard < ApplicationRecord
	enum page_type: {contact_us: 0, about_us: 1, terms: 2, privacy: 3}
end

app/models/post_ad.rb
class PostAd < ApplicationRecord
  mount_uploaders :avatars, ImageUploader
  belongs_to :user
  enum status: {running: 0,stopped: 1}
  belongs_to :sub_category
  has_many :replies, dependent: :destroy
  has_many :reports, dependent: :destroy
  has_one_attached :clip
  #mount_uploader :video, VideoUploader 
  # belongs_to :continent
  # belongs_to :country
  # belongs_to :state
  belongs_to :city
  belongs_to :category
  # belongs_to :user
end

app/models/reply.rb
class Reply < ApplicationRecord
  belongs_to :user
  belongs_to :post_ad
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :user
  belongs_to :post_ad
end

app/models/state.rb
class State < ApplicationRecord
  has_many :cities
  belongs_to :country
  has_many :post_ads
end

app/models/sub_category.rb
class SubCategory < ApplicationRecord
  has_many :post_ads
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :omniauthable, omniauth_providers: [:google_oauth2]
  has_many :post_ads
  has_many :replies
  has_one  :user_information
  

  def self.from_google(email:, full_name:, uid:, avatar_url:)
    return nil if email.blank?
    create_with(uid: uid, full_name: full_name, avatar_url: avatar_url).find_or_create_by!(email: email)
  end
  
  
end

app/models/user_information.rb
class UserInformation < ApplicationRecord
	belongs_to :user
	WHITELIST_PARAMS = [:name, :email, :address, :phone, :zipcode, :user_id]
	
end

app/controllers/post_ads_controller.rb
class PostAdsController < ApplicationController
  before_action :set_post_ad, only: %i[ show edit update destroy ]
  skip_before_action :authenticate, only: [:show, :published_adz]


  # GET /post_ads or /post_ads.json
  def index
    @post_ads = current_user.post_ads
  end

  # GET /post_ads/1 or /post_ads/1.json
  def show
  end

  def published_adz
    @category_id = params[:category_id]
    @sub_category_id = params[:cat_id]
    @post_ads =  PostAd.where(city_id: params[:city_id] , category_id: params[:category_id], sub_category_id: params[:cat_id]).running
    @city = City.find_by(id: params[:city_id])
    @cities = Country.find_by(id: @city.country.id).cities
  end


  # GET /post_ads/new
  def new
    @category_id = params[:category_id]
    @sub_category_id = params[:cat_id]
    @city = City.find_by(id: params[:city_id])
    if @city.present? && @sub_category_id.present? && @category_id.present?
      @post_ad = PostAd.new(user_id: current_user.id)
    else
      redirect_to dashboard_show_path, alert:"Please select country, category and sub_category to post add on location!"
    end
  end

  # GET /post_ads/1/edit
  def edit
    postad = PostAd.find_by(id: params[:id])
    city_id = postad.city_id
    @city = City.find_by(id: city_id)
  end

  # POST /post_ads or /post_ads.json
  def create
    @post_ad = PostAd.new(post_ad_params)
    respond_to do |format|
      if @post_ad.save
        PostMailer.new_post_email(@post_ad.email).deliver_now
        if params[:city_ids].present?
          params[:city_ids].each do |e|
           post_ad = PostAd.create(post_ad_params)
           post_ad.update(city_id: e) 
          end
          redirect_to specific_charges_path(price: params[:city_ids].size * 10) and return
        end
        format.html { redirect_to @post_ad, notice: "Post ad was successfully created." }
        format.json { render :show, status: :created, location: @post_ad }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post_ad.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /post_ads/1 or /post_ads/1.json
  def update
    respond_to do |format|
      if @post_ad.update(post_ad_params)
        format.html { redirect_to @post_ad, notice: "Post ad was successfully updated." }
        format.json { render :show, status: :ok, location: @post_ad }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post_ad.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /post_ads/1 or /post_ads/1.json
  def destroy
    @post_ad.destroy
    respond_to do |format|
      format.html { redirect_to post_ads_url, notice: "Post ad was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post_ad
      @post_ad = PostAd.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_ad_params
      params.require(:post_ad).permit(:title, :description, :location, :phone, :keywords, :email, :category_id, :sub_category_id, :city_id, :get_response, :terms_privacy, :business, :personal, :price, :clip, :negotiable, :zipcode, :status, :user_id, {avatars: []}, city_ids: [])
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/continents_helper.rb
module ContinentsHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/post_ads_helper.rb
module PostAdsHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/views/post_ads/_form.html.erb
<div class="page" style =" background-color: white;">

    <div class="avt-post-wrapper section">

      <div class="container">

        <div class="avt-post">
          <!-- Start Form -->
          <%= form_with(model: post_ad, local: true) do |form| %>
              <% if post_ad.errors.any? %>
                <div id="error_explanation">
                  <h2><%= pluralize(post_ad.errors.count, "error") %> prohibited this post_ad from being saved:</h2>

                  <ul>
                  <% post_ad.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                  </ul>
                </div>
              <% end %>

            <fieldset>

              <div class="product-section avtpost-fields">

                <div class="row">

                  <div class="col-xs-12">

                    <h3 ><%= t('write_ad')%></h3>

                  </div>

                  <div class="col-md-12">
                    <div class="col-md-8">

                      <div class="row form-group">

                        <label ><%= t('title_ad')%></label>

                          <%= form.text_field :title, required: true, :class => "form-control"%>                   
                      </div>
                      <div class="row form-group">

                        <label><%= t('price_ad')%> <span>($ USD)</span> : </label>

                              <%= form.text_field :price, class:"form-control"%>

                      </div>

                      <div class="row form-group">

                        <label><%= t('description_ad')%> </label>
                          <%= form.cktext_area :description, class: 'form-control descr', ckeditor: { language: 'en'} %>
                      </div>
                    
                      <div class="row form-group">

                        <label><%= t('location_ad')%></label>

                          <%= form.text_field :location, required: true, :class => "form-control", :placeholder => t('enter_location_ad')%>
                    </div><!-- post-inner -->
                     <div class="row form-group">

                        <label><%= t('zipcode_ad')%> </label>

                          <%= form.text_field :zipcode, required: true, :class => "form-control", :placeholder => t('enter_zip_ad')%>
                    </div><!-- post-inner -->
                    <div class="checkbox choose-option">

                        <%= form.check_box :negotiable %>
                        <label style="color: black;"><%= t('farward_mail')%></label>


                     </div>
                     <div class="row form-group">

                        <label><%= t('contact_ad')%></label>

                          <%= form.text_field :email, value: post_ad&.user&.email, :readonly => true, class:"form-control"%>

                      </div>
                      <div class="row form-group">

                        <label><%= t('phone_ad')%></label>

                          <%= form.text_field :phone, required: true, class:"form-control"%>

                      </div>

                      <div class="row form-group">
                        <label><%= t('status_ad')%></label>
                        <%= form.select :status, options_for_select(PostAd.statuses.keys, selected: post_ad.status) %>

                      </div>

                       <div class="row form-group">

                        <label ><%= t('upload_pic')%></label>

                          <div class="upload-section">

                            <label class="upload-image" for="uploadOne">
                              <%= form.file_field :avatars, multiple: true, :id => "uploadOne" %>
  
                            </label>                    

                            <label class="upload-image" for="uploadTwo">

                              <%= form.file_field :avatars, multiple: true, :id => "uploadTwo" %>

                            </label>                      

                            <label class="upload-image" for="uploadThree">

                              <%= form.file_field :avatars, multiple: true, :id => "uploadThree" %>

                            </label>  

                            <label class="upload-image" for="uploadFour">

                               <%= form.file_field :avatars, multiple: true, :id => "uploadFour" %>

                            </label>  
                            <label class="upload-image" for="uploadFive">

                               <%= form.file_field :avatars, multiple: true, :id => "uploadFive" %>

                            </label>  

                          </div>

                      </div>
                      <div class="row form-group">
                        <label ><%= t('upload_vid')%> (<span style="font-size: 12px;"><%= t('upload_size')%></span>) </label>
                        <div class="upload-section">
                        <label class="upload-image" >

                               <%= form.file_field :clip  %>

                            </label> 
                            </div> 
                      </div>


                  </div>
                </div>

                     <div class="row form-group">
                      
                        <div class="col-md-8">
                        <% if post_ad.city_id.present? %>
                          <%= form.hidden_field :city_id, value: post_ad.city_id  %>
                        <%else%>
                          <%= form.hidden_field :city_id, value: @city.id  %>
                        <%end%>
                        </div>

                      </div>

                      <div class="row form-group">
                        <div class="col-md-8">
                        <% if post_ad.category_id.present? %>
                          <%= form.hidden_field :category_id, value: post_ad.category_id %>
                        <%else%>
                          <%= form.hidden_field :category_id, value: @category_id  %>
                        <%end%>
                        </div>

                      </div>

                      <div class="row form-group">
                        <div class="col-md-8">
                        <% if post_ad.sub_category_id.present? %>
                        <%= form.hidden_field :sub_category_id, value: post_ad.sub_category_id %>
                        <%else%>
                        <%= form.hidden_field :sub_category_id, value: @sub_category_id %>
                        <%end%>

                        </div>

                      </div>

                </div>

              </div><!-- product-section -->



               <!-- <div class="seller-section avtpost-fields">

                <div class="row">

                  <div class="col-xs-12">

                    <h3>Seller Information</h3>

                  </div>

                  <div class="col-md-6">

                    <div class="post-inner">

                      <div class="row form-group">

                        <label class="col-md-4">Contact Name: </label>

                        <div class="col-md-8">
                          
                          <%= form.text_field :email, value: post_ad&.user&.full_name, :readonly => true, class:"form-control"%>

                        </div>

                      </div>

                    </div>

                  </div>

                </div>  -->

              </div><!-- seller-section -->



              <div class="seller-option avtpost-fields hiden">

                <div class="row">

                  <div class="col-md-12">

                    <h3><%= t('upgrade_form')%></h3>

                  </div>

                  <div class="col-md-12">

                    <div class="post-inner">

                      <div class="form-group">

                        <span><%= t('near_city_ad')%><span>$10.00</span> </span>
                        <ul>
                          <% @city.country.cities.where.not(id: @city.id).first(8).each do |e|%>
                            <li><%= check_box_tag "city_ids[]", e.id, false, :id => "city_ids_#{e.id}" %><span , style="margin-left: 5px;"><%= e.name%> 10$</span></li>
                          <%end%>
                        </ul>

                        <div class="premium-avts">

                         <!--  <ul>

                            <li class="premium-avt">

                              <input type="radio" name="premiumAvt" value="option-one" id="option-one">

                              <label for="option-one">Regular Ad</label>

                              <span>$00.00</span>

                            </li>

                            <li class="premium-avt">

                              <input type="radio" name="premiumAvt" value="option-two" id="option-two">

                           <label for="option-two">Top Featured Ads</label>

                              <span>$59.00</span>

                            </li>

                             <li class="premium-avt">

                              <input type="radio" name="premiumAvt" value="option-three" id="option-three">

                              <label for="option-three">Urgent Ads</label>

                              <span>$79.00</span>

                            </li>             

                          </ul> -->

                        </div>

                      </div>

                    </div><!-- post-inner -->

                  </div>

                  <!-- <div class="col-md-12">

                    <div class="post-inner">

                      <div class="form-group">

                        <span>Please select the preferred payment method: </span>

                        <div class="payment-options">

                          <ul>

                            <li class="payment-option">

                              <input type="radio" name="payment-option" value="payment-one">

                              <label for="payment-one">Direct Bank Transfer</label>

                            </li>

                            <li class="payment-option">

                              <input type="radio" name="payment-option" value="payment-two">

                              <label for="payment-two">Cheque Payment</label>

                            </li>

                            <li class="payment-option">

                              <input type="radio" name="payment-option" value="payment-three">

                              <label for="payment-three">Credit Card</label>

                            </li>             

                          </ul>

                        </div>

                      </div>

                    </div>

                  </div>
 -->
                </div>

              </div><!-- seller-option -->
                 <div class="g-recaptcha" data-sitekey="6LcEyJ4aAAAAAPmFWrlMuiif1gkQanrcBreg2Pk7
">
                   
                 </div>

              <div class="submit-section">

                <div class="ad-condition checkbox">

                  <label for="submit-post">

                    <%= form.check_box :terms_privacy, required: true %>

                    <%= t('terms_ad')%> <a href="#"> <%= t('condition_ad')%></a> <%= t('terms_and')%>

                                    <a href="#"><%= t('posting_ad')%></a>.

                  </label>

                </div>

                <div class="submit-button">
                    <%= form.hidden_field :user_id, value: current_user.id %>
                    <%= form.submit t('sub_post_btn'), :class => "btn btn-primary", :style => "background-color: red;  font-weight: bold;"  %>

                </div>

              </div>

            </fieldset>

          <% end %>  <!--End Form -->

        </div>

      </div>

    </div> <!-- avt-post -->

  </div>  <!-- page -->

<script type="text/javascript">
$(document).ready(function(){    
    //Check if the current URL contains '#'
    if(document.URL.indexOf("#")==-1){
        // Set the URL to whatever it was plus "#".
        url = document.URL+"#";
        location = "#";

        //Reload the page
        location.reload(true);
    }
});
</script>

app/views/post_ads/edit.html.erb
<div class ="container-fluid" style="float: right;">
  <%if current_user.present?%>
     <button style= "float: right; margin-right: 20px; margin-top: 20px;"><%= link_to "Manage Ads", post_ads_path, :style => "font-weight: bold; color: black;", :class=>"homeshow" %>
  <%end%></button>
</div>
<h3><%= t('postad_edit_h')%></h3>

<%= render 'form', post_ad: @post_ad %>

<%= link_to 'Show', @post_ad %> |
<%= link_to 'Back', post_ads_path %>

app/views/post_ads/index.html.erb
<div class="container" style="color: white;">
<p id="notice"><%= notice %></p>

<h1><%= t('post_heading_postads')%></h1>

<table class="table table-bordered" >
  <thead>
    <tr>
      <th><%= t('title_postads')%></th>
      <th><%= t('status_postads')%></th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @post_ads.each do |post_ad| %>
    
      <tr>
        <td><%= post_ad.title %></td>
        <% if post_ad.stopped? %>
          <td style="color: red;"><%= post_ad.status%></td>
        <%else%>
          <td style="color: green;"><%= post_ad.status%></td>
      <% end %>
        <td><%= link_to t('view_all_reply'), replies_path(id: post_ad.id) %></td>
        <td><%= link_to t('show_postads'), post_ad %></td>
        <td><%= link_to t('edit_postads'), edit_post_ad_path(post_ad) %></td>
        <td><%= link_to t('destroy_postads'), post_ad, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
</div>

app/views/post_ads/new.html.erb
<div class="container" style="margin-top: 20px;">

<h1 style="color: white;"><%= t('postad_heading')%>
	<%if current_user.present?%>
     <%= link_to t('live_ad_btn'), published_adz_post_ads_path(cat_id: @sub_category_id, city_id: @city&.id, category_id: @category_id), :class=>"btn", :style => " background-color: white; font-weight: bold; color: black; float: right;" %>
     <% end %>
</h1>


<%= render 'form', post_ad: @post_ad %>

<%= link_to 'Back', post_ads_path %>
</div>

app/views/post_ads/published_adz.html.erb
<div class="container publ1" style="color: black; background-color: white;" >
<p id="notice"><%= notice %></p>
<%@cities.each do |e|%>
 <% if e.id == @city.id%>
 <%= link_to e.name, published_adz_post_ads_path(city_id: e.id, cat_id: @sub_category_id, category_id: params[:category_id]), :style => "color: black;"%>||
 <%else%>
  <%= link_to e.name, published_adz_post_ads_path(city_id: e.id, cat_id: @sub_category_id, category_id: params[:category_id]), :style => "color: red;"%> ||
<%end%>
<%end%>

<h1><%= t('live_ad_page')%></h1>

<table class="table" >
  <thead>
    <tr>

      <!-- <th>Location</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Description</th>
      <th>status</th> -->

    </tr>
  </thead>

  <tbody>
    <% @post_ads.group("date(post_ads.created_at)").count.keys.reverse.each do |e| %>
      <div style="background-image: linear-gradient(to right, #eeeeee, black);"><p style="color:red"><%= e.strftime("%B %d, %Y") %> </p></div>
    <% @post_ads.where('created_at BETWEEN ? AND ?', e.beginning_of_day, e.end_of_day).each do |post_ad| %>
  
        <p><%= link_to post_ad.title, post_ad, :style => "color: black;", :class => "publi" %><strong> <span style="font-size: 16px;"> [ <%= post_ad.location%> ]</span> <%= post_ad.created_at.strftime("%H:%M:%S") %></strong></p>  
      
    <% end %>
    
    <% end %>
  </tbody>
</table>

<br>
</div>

app/views/post_ads/show.html.erb
<div class ="container addpage">
  <%if current_user.present?%>
     <%= link_to "Manage Ads", post_ads_path, :style => "font-weight: bold; color: black; float: right;", :class=>"homeshow" %>
  <%end%>
</div>
<div class="container" style="margin-top: 30px; background-color: white; width: 95%;">
  <%= link_to t('postad_show_reply_btn'), new_reply_path(id: @post_ad.id, reply: true), class:"btn", style:"background-color: #f1de30; color: black;" %><!-- replies -->
  <%= link_to t('postad_show_report_btn'), recapcha_submit_reports_path(id: @post_ad.id, user_id: current_user&.id), class:"btn", style:"background-color: red; color: black;" %>
    <p>
      <h5 style="color: black;" class="spcerm"><strong><%= t('postad_show_title')%> <%= @post_ad.title %></strong></h5>
    </p>
    <p>
      <h5 style="color: black;" class="spcerm"><strong><%= t('postad_show_price')%> <%= @post_ad.price %></strong></h5>
    </p>
    <h4 style="color: red; text-decoration: underline;"><strong><%= t('postad_show_overview')%></strong></h4>
<div class="container" style="color: black;">
  <p class="spcerm">
    <strong><%= t('postad_show_post_id')%></strong>
    <span><%= @post_ad.id %></span>
  </p>
  <p class="spcerm">
    <strong><%= t('postad_show_zip')%></strong>
    <span><%= @post_ad.zipcode %></span>
  </p>

  <p class="spcerm"> 
    <strong><%= t('postad_show_phone')%></strong>
    <span><%= @post_ad.phone %></span>
  </p>

  <p class="spcerm">
    <strong><%= t('postad_show_post_in')%></strong>
    <span><%= @post_ad.location %></span>
  </p>


 <!--  <p class="spcerm">
    <strong>Keywords:</strong>
    <span><%= @post_ad.keywords %></span>
  </p> -->
  <!-- 
  <p>
    <strong>Nego:</strong>
    <%= @post_ad.negotiable %>
  </p> -->

  <p class="spcerm1" style="margin-top: -5px;">
    <strong><%= t('postad_show_title')%></strong>
    <span><%= @post_ad.email %></span>
  </p>
  <p class="spcerm1" style="margin-top: -9px;">
    <strong><%= t('postad_show_title')%></strong>
    <span><%= @post_ad.city.name %>, <%= @post_ad.category.name%>, <%= @post_ad.sub_category.name%></span>
  </p>

</div>
<h4 style="color: red; text-decoration: underline; margin-top: -6px;"><strong><%= t('postad_show_desc')%></strong></h4>
      <div class="container" style="color: black; padding-bottom: 50px;">
        <p ><%= @post_ad.description.html_safe %></p>
      </div>

    <div class="container">
      <% @post_ad.avatars.each do |avatar|%>
      <%= image_tag avatar.url, style: 'width: 74%; margin-bottom:10px; border-radius: 10px; float:left;' %>
      <%end%>
    </div>
    <h4 style="float: left; color: red; text-decoration: underline; margin-top: -6px;"><strong><%= t('postad_show_video')%></strong></h4><br>
    <div class="container">
      <% if @post_ad&.clip_blob.present? %>
      <%= video_tag(url_for(@post_ad&.clip), style: 'width: 74%; margin-bottom:10px; border-radius: 10px; margin-left: -40px;', controls: "") %>
      <%end%>
    </div>
<!-- <p>
  <strong>Get response:</strong>
  <%= @post_ad.get_response %>
</p>

<p>
  <strong>Terms privacy:</strong>
  <%= @post_ad.terms_privacy %>
</p>

<p>
  <strong>User Name:</strong>
  <%= @post_ad.user.full_name %>
</p>
<p>
  <strong>Avatar:</strong>
  <%= image_tag(@post_ad.user.avatar_url, height: 50) %>
</p>
<p>
  <strong>Email:</strong>
  <%= @post_ad.user.email %>
</p> -->


</div>