config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', sessions: 'users/sessions'  }
  scope "(:locale)", :locale => /en|ru|ar|ch|sp|fr|it/ do
    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
    resources :reports do 
      collection do
        get :recapcha_submit
      end
    end
    resources :replies
    mount Ckeditor::Engine => '/ckeditor'
    resources :sub_categories do
      collection do
        get :disclaimer
        get :disclaimer_2
        get :subcat
      end
    end
    resources :categories do
      collection do
        get :catpage
        get :search
      end
    end
    resources :cities
    resources :states
    resources :countries
    resources :continents
    resources :charges, only: [:new, :create] do
      collection do
        get :pay
        get :specific
      end
    end
   
    
    root 'dashboard#main'
    get 'dashboard/catshow'
    get 'dashboard/show'
    get  'dashboard/signout'
    get  'dashboard/decide'
    get  'dashboard/search'
    get 'dashboard/conshow'
    #root 'post_ads#index'
    resources :post_ads do
      collection do
        get :published_adz
      end
    end
    get 'dashboard/login_page'
    get 'dashboard/store'
    get 'dashboard/giveaway'
    get 'dashboard/contact_us'
    get 'dashboard/about_us'
    get 'dashboard/terms'
    get 'dashboard/privacy'
    get 'reports/recaptcha'
    resources :user_informations do 
      collection do
        get :page 
      end
    end
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :sub_categories
  has_many :post_ads
end

app/models/city.rb
class City < ApplicationRecord
  has_many :categories
  belongs_to :country
  has_many :post_ads
end

app/models/continent.rb
class Continent < ApplicationRecord
  has_many :countries
  has_many :post_ads
  translates :name, touch: true, :fallbacks_for_empty_translations => true
end

app/models/country.rb
class Country < ApplicationRecord
  has_many :cities
  belongs_to :continent
  has_many :post_ads
end

app/models/dashboard.rb
class Dashboard < ApplicationRecord
	enum page_type: {contact_us: 0, about_us: 1, terms: 2, privacy: 3}
end

app/models/post_ad.rb
class PostAd < ApplicationRecord
  mount_uploaders :avatars, ImageUploader
  belongs_to :user
  enum status: {running: 0,stopped: 1}
  belongs_to :sub_category
  has_many :replies, dependent: :destroy
  has_many :reports, dependent: :destroy
  has_one_attached :clip
  #mount_uploader :video, VideoUploader 
  # belongs_to :continent
  # belongs_to :country
  # belongs_to :state
  belongs_to :city
  belongs_to :category
  # belongs_to :user
end

app/models/reply.rb
class Reply < ApplicationRecord
  belongs_to :user
  belongs_to :post_ad
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :user
  belongs_to :post_ad
end

app/models/state.rb
class State < ApplicationRecord
  has_many :cities
  belongs_to :country
  has_many :post_ads
end

app/models/sub_category.rb
class SubCategory < ApplicationRecord
  has_many :post_ads
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :omniauthable, omniauth_providers: [:google_oauth2]
  has_many :post_ads
  has_many :replies
  has_one  :user_information
  

  def self.from_google(email:, full_name:, uid:, avatar_url:)
    return nil if email.blank?
    create_with(uid: uid, full_name: full_name, avatar_url: avatar_url).find_or_create_by!(email: email)
  end
  
  
end

app/models/user_information.rb
class UserInformation < ApplicationRecord
	belongs_to :user
	WHITELIST_PARAMS = [:name, :email, :address, :phone, :zipcode, :user_id]
	
end

app/controllers/sub_categories_controller.rb
class SubCategoriesController < ApplicationController
  before_action :set_sub_category, only: %i[ show edit update destroy subcat ]
  skip_before_action :authenticate, only: [:index, :disclaimer, :subcat, :disclaimer_2]
  # GET /sub_categories or /sub_categories.json
  def index
    @category = Category.find_by(id: params[:id])
    @city = City.find_by(id: params[:city_id])
    @sub_categories = @category.sub_categories
  end

  # GET /sub_categories/1 or /sub_categories/1.json
  def show
  end
  def subcat
    @category = Category.find_by_id(params[:id])
    @sub_categories = @category.sub_categories
  end
  # GET /sub_categories/new
  def new
    @sub_category = SubCategory.new
  end
  def disclaimer
    @cat_id = SubCategory.find_by(id: params[:id])
    @category = Category.find_by(id: params[:category_id])
    @city = City.find_by(id: params[:city_id])
    @sub_categories = @category.sub_categories
    
  end
  def disclaimer_2
    @cat_id = SubCategory.find_by(id: params[:sub_category])
    @category = Category.find_by(id: params[:category_id])
    @city = City.find_by(id: params[:city_id])
    @sub_categories = @category.sub_categories
    
  end

  # GET /sub_categories/1/edit
  def edit
  end

  # POST /sub_categories or /sub_categories.json
  def create

    @sub_category = SubCategory.new(sub_category_params)

    respond_to do |format|
      if @sub_category.save
        format.html { redirect_to @sub_category, notice: "Sub category was successfully created." }
        format.json { render :show, status: :created, location: @sub_category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @sub_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sub_categories/1 or /sub_categories/1.json
  def update
    respond_to do |format|
      if @sub_category.update(sub_category_params)
        format.html { redirect_to @sub_category, notice: "Sub category was successfully updated." }
        format.json { render :show, status: :ok, location: @sub_category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @sub_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sub_categories/1 or /sub_categories/1.json
  def destroy
    @sub_category.destroy
    respond_to do |format|
      format.html { redirect_to sub_categories_url, notice: "Sub category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sub_category
      @sub_category = SubCategory.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sub_category_params
      params.require(:sub_category).permit(:name)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/post_ads_helper.rb
module PostAdsHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/sub_categories_helper.rb
module SubCategoriesHelper
end

app/views/sub_categories/_form.html.erb
<%= form_with(model: sub_category, local: true) do |form| %>
  <% if sub_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sub_category.errors.count, "error") %> prohibited this sub_category from being saved:</h2>

      <ul>
      <% sub_category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sub_categories/disclaimer.html.erb
<div class="container dis1" style="width: auto; background-color: black; ">
	
	<center style= "margin: 0px -50px 0px -50px;">
		<div class="container" style="background-color: white; width: 70%; border: 5px solid red;">
			<h3><%= t('disclaimer_h1')%></h3>
		 <p style="text-align: justify;"><%= t('disclaimer_p1')%> <a href = "postadz.com" >PostAdz.com</a> <%= t('disclaimer_p2')%><a href ="/dashboard/privacy"><%= t('d_privacy')%></a><%= t('d_and')%> <a href = "dashboard/terms"><%= t('d_terms')%></a> <%= t('disclaimer_p3')%></p>
        <%if current_user.present?%>
		<%= link_to t('d_21'), new_post_ad_path(cat_id: @cat_id, city_id: @city&.id, category_id: @category.id), class:"btn", style:"background-color: red; color: black;" %>
		<%= link_to t('d_exit'), sub_categories_path, class:"btn", style:"background-color: red; color: black;" %>
		<%else%>
		    <%= link_to t('d_21'), published_adz_post_ads_path(cat_id: @cat_id, city_id: @city&.id, category_id: @category.id), class:"btn", style:"background-color: red; color: black;" %>
		<%= link_to t('d_exit'), sub_categories_path, class:"btn", style:"background-color: red; color: black;" %>
		<%end%>

	</div></center>
</div>

app/views/sub_categories/disclaimer_2.html.erb
<div class="container" style="width: auto; background-color: black; margin: 40px 50px 0px 50px;">
	
	<center style= "margin: 0px -50px 0px -50px;">
		<div class="container" style="background-color: white; width: 70%; border: 5px solid red;">
			<h3><%= t('disclaimer_h1')%></h3>
		 <p style="text-align: justify;"><%= t('disclaimer_p1')%> <a href = "postadz.com" >PostAdz.com</a> <%= t('disclaimer_p2')%> <a href ="/dashboard/privacy"><%= t('d_privacy')%></a><%= t('d_and')%> <a href = "dashboard/terms"><%= t('d_terms')%></a> <%= t('disclaimer_p3')%></p>
        <%if current_user.present?%>
		<%= link_to t('d_21'), dashboard_conshow_path(category_id: @category.id, sub_category: @cat_id.id), class:"btn", style:"background-color: red; color: black;" %>
		<%= link_to t('d_exit'), subcat_sub_categories_path(id: @category.id), class:"btn", style:"background-color: red; color: black;" %>
		<%else%>
		    <%= link_to t('d_21'), dashboard_conshow_path(category_id: @category.id, sub_category: @cat_id.id), class:"btn", style:"background-color: red; color: black;" %>
		<%= link_to t('d_exit'), subcat_sub_categories_path(id: @category.id), class:"btn", style:"background-color: red; color: black;" %>
		<%end%>

	</div></center>
</div>

app/views/sub_categories/edit.html.erb
<h1>Editing Sub Category</h1>

<%= render 'form', sub_category: @sub_category %>

<%= link_to 'Show', @sub_category %> |
<%= link_to 'Back', sub_categories_path %>

app/views/sub_categories/index.html.erb
<div class="container">
<h2><%= @category&.name%></h2>
  <div class="row" style="margin: 1px;">
    <div class="col-md-6">
      <div style="background-color: #F3F6FB; font-size: 25px; border-radius: 5px; margin-bottom: 2px; padding-left: 10px; color: red;"></div>
      <% @sub_categories&.each do |cat|%>
        <%if current_user.present?%>
          <%if @category&.name == "Love Personals"%>
            <li style="list-style-type: square; color: #fcea46; font-size: 2em;">
            <%= link_to cat&.name, disclaimer_sub_categories_path(id: cat.id, city_id: @city&.id, category_id: @category.id), :class => "hoverclr", :style => "color: white; font-size: 20px;"%></li>
          <%else%>  
            <li style="list-style-type: square; color: #fcea46; font-size: 2em;"><%= link_to cat&.name, new_post_ad_path(cat_id: cat.id, city_id: @city&.id, category_id: @category.id), :class => "hoverclr", :style => "color: white; font-size: 20px;"%></li>
          <%end%>
         <%else%>
                <%if @category&.name == "Love Personals"%>
                  <li style="list-style-type: square; color: #fcea46; font-size: 2em;">
                  <%= link_to cat&.name, disclaimer_sub_categories_path(id: cat.id, city_id: @city&.id, category_id: @category.id), :class => "hoverclr", :style => "color: white; font-size: 20px;"%></li>
                  <%else%>
                    <li style="list-style-type: square; color: #fcea46; font-size: 2em;">
                  <%= link_to cat&.name, published_adz_post_ads_path(cat_id: cat.id, city_id: @city&.id, category_id: @category.id), :class => "hoverclr", :style => "color: white; font-size: 20px;"%></li>
                  <%end%>
                 <%end%>
        <%end%>
    </div>
  </div>
</div>

app/views/sub_categories/new.html.erb
<h1>New Sub Category</h1>

<%= render 'form', sub_category: @sub_category %>

<%= link_to 'Back', sub_categories_path %>

app/views/sub_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @sub_category.name %>
</p>

<%= link_to 'Edit', edit_sub_category_path(@sub_category) %> |
<%= link_to 'Back', sub_categories_path %>

app/views/sub_categories/subcat.html.erb
<div class="container">
<h3><%= @category&.name%></h3>
  <div class="row" style="margin: 1px;">
    <div class="col-md-6">
      <div style="background-color: #F3F6FB; font-size: 25px; border-radius: 5px; margin-bottom: 2px; padding-left: 10px; color: red;"></div>
      <% @sub_categories&.each do |cat|%>
      <%if current_user.present?%>
          <%if @category&.name == "Love Personals"%>
            <li style="list-style-type: square; color: #fcea46; font-size: 2em;">
            <%= link_to cat&.name, disclaimer_2_sub_categories_path(category_id: @category.id, sub_category: cat.id), :class => "hoverclr", :style => "color: white; font-size: 20px;"%></li>
          <%else%>  
            <li style="list-style-type: square; color: #fcea46; font-size: 2em;"><%= link_to cat&.name, dashboard_conshow_path(category_id: @category.id, sub_category: cat.id), :class => "hoverclr", :style => "color: white; font-size: 20px;"%></li>
          <%end%>
         <%else%>
                <%if @category&.name == "Love Personals"%>
                  <li style="list-style-type: square; color: #fcea46; font-size: 2em;">
                    <%= link_to cat&.name, disclaimer_2_sub_categories_path(category_id: @category.id, sub_category: cat.id), :class => "hoverclr", :style => "color: white; font-size: 20px;"%></li>
                  <%else%>
                    <li style="list-style-type: square; color: #fcea46; font-size: 2em;">
                  <%= link_to cat&.name, dashboard_conshow_path(category_id: @category.id, sub_category: cat.id), :class => "hoverclr", :style => "color: white; font-size: 20px;"%></li>
                  <%end%>
                 <%end%>
        <%end%>
    </div>
  </div>
</div>