config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', sessions: 'users/sessions'  }
  scope "(:locale)", :locale => /en|ru|ar|ch|sp|fr|it/ do
    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
    resources :reports do 
      collection do
        get :recapcha_submit
      end
    end
    resources :replies
    mount Ckeditor::Engine => '/ckeditor'
    resources :sub_categories do
      collection do
        get :disclaimer
        get :disclaimer_2
        get :subcat
      end
    end
    resources :categories do
      collection do
        get :catpage
        get :search
      end
    end
    resources :cities
    resources :states
    resources :countries
    resources :continents
    resources :charges, only: [:new, :create] do
      collection do
        get :pay
        get :specific
      end
    end
   
    
    root 'dashboard#main'
    get 'dashboard/catshow'
    get 'dashboard/show'
    get  'dashboard/signout'
    get  'dashboard/decide'
    get  'dashboard/search'
    get 'dashboard/conshow'
    #root 'post_ads#index'
    resources :post_ads do
      collection do
        get :published_adz
      end
    end
    get 'dashboard/login_page'
    get 'dashboard/store'
    get 'dashboard/giveaway'
    get 'dashboard/contact_us'
    get 'dashboard/about_us'
    get 'dashboard/terms'
    get 'dashboard/privacy'
    get 'reports/recaptcha'
    resources :user_informations do 
      collection do
        get :page 
      end
    end
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :sub_categories
  has_many :post_ads
end

app/models/city.rb
class City < ApplicationRecord
  has_many :categories
  belongs_to :country
  has_many :post_ads
end

app/models/continent.rb
class Continent < ApplicationRecord
  has_many :countries
  has_many :post_ads
  translates :name, touch: true, :fallbacks_for_empty_translations => true
end

app/models/country.rb
class Country < ApplicationRecord
  has_many :cities
  belongs_to :continent
  has_many :post_ads
end

app/models/dashboard.rb
class Dashboard < ApplicationRecord
	enum page_type: {contact_us: 0, about_us: 1, terms: 2, privacy: 3}
end

app/models/post_ad.rb
class PostAd < ApplicationRecord
  mount_uploaders :avatars, ImageUploader
  belongs_to :user
  enum status: {running: 0,stopped: 1}
  belongs_to :sub_category
  has_many :replies, dependent: :destroy
  has_many :reports, dependent: :destroy
  has_one_attached :clip
  #mount_uploader :video, VideoUploader 
  # belongs_to :continent
  # belongs_to :country
  # belongs_to :state
  belongs_to :city
  belongs_to :category
  # belongs_to :user
end

app/models/reply.rb
class Reply < ApplicationRecord
  belongs_to :user
  belongs_to :post_ad
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :user
  belongs_to :post_ad
end

app/models/state.rb
class State < ApplicationRecord
  has_many :cities
  belongs_to :country
  has_many :post_ads
end

app/models/sub_category.rb
class SubCategory < ApplicationRecord
  has_many :post_ads
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :omniauthable, omniauth_providers: [:google_oauth2]
  has_many :post_ads
  has_many :replies
  has_one  :user_information
  

  def self.from_google(email:, full_name:, uid:, avatar_url:)
    return nil if email.blank?
    create_with(uid: uid, full_name: full_name, avatar_url: avatar_url).find_or_create_by!(email: email)
  end
  
  
end

app/models/user_information.rb
class UserInformation < ApplicationRecord
	belongs_to :user
	WHITELIST_PARAMS = [:name, :email, :address, :phone, :zipcode, :user_id]
	
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy]
  skip_before_action :authenticate, only: [:index, :catpage, :search]
  # GET /categories or /categories.json
  def index
    @city = City.find_by(id: params[:id])
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end
  def search
    @category = Category.where('name ILIKE ?', "%#{params[:search]}%")
  end

  
  def catpage
    @categories = Category.all
  end  

  # GET /categories/new
  def new
    @category = Category.new
  end
  # def search
  #   @cities = Category.where('name ILIKE ?', "%#{params[:search]}%")
  # end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/continents_helper.rb
module ContinentsHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/post_ads_helper.rb
module PostAdsHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/catpage.html.erb
<div class="container" style="margin-top: 30px;">
<h3><%= t('catpage_heading')%></h3>
<div><%= form_tag :search_categories, method: :get do %>
  <%= text_field_tag :search, nil, class:"form-control fa fa-search", placeholder: t('search_by_catpage'), required: true, :id => "mysearch"%>
<%end%>	
</div>
<div class="row" style="margin: 1px;">
      <div class="col-md-6">
      <div style="background-color: #F3F6FB; font-size: 25px; border-radius: 5px; margin-bottom: 2px; padding-left: 10px; color: red;"></div>
      <% @categories&.each do |cat|%>        
       		<li style="list-style-type: square; color: #fcea46; font-size: 2em;">
        	<%= link_to cat&.name, subcat_sub_categories_path(id: cat.id), :class => "hoverclr", :style => "color: white; font-size: 20px;"%></li>
      <%end%>

  </div>
</div>
</div>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<div onload="LoadOnce()" class="container">
<h2><%= @city&.name%></h2>
  <div class="row" style="margin: 1px;">
      <div class="col-md-6">
      <div style="background-color: #F3F6FB; font-size: 25px; border-radius: 5px; margin-bottom: 2px; padding-left: 10px; color: red;"></div>
      <% @categories&.each do |cat|%>        
       		<li style="list-style-type: square; color: #fcea46; font-size: 2em;">
        	<%= link_to cat&.name, sub_categories_path(id: cat.id, city_id: @city.id), :class => "hoverclr", :style => "color: white; font-size: 20px;"%></li>
      <%end%>

  </div>
</div>
</div>
<script>
	function LoadOnce()
				{ 
					window.location.reload(); 
				} 
</script>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/search.html.erb
<div class="container">
  <div class="row" style="margin: 1px;">
    <div class="col-md-6">
      <div style="background-color: #F3F6FB; font-size: 25px; border-radius: 5px; margin-bottom: 2px; padding-left: 10px; color: red;"></div>
      <% if @category.present? %>
      <% @category&.each do |cat|%>
        <p><%= link_to cat&.name, subcat_sub_categories_path(id: cat.id)%></p>
      <%end%>
      <%else%>
       <H3>No Results found!</H3>
      <%end%>
    </div>
  </div>

</div>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>